sources:
  - id: "shadergraph_nodes_or-gpt4o-mini"
    url: "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Node-Library.html"
    title: "Unity Shadergraph node descriptions"
    description: "Require glossary listing all fields"
    instruction: |
      From the crawled content, extract all mentioned model names along with their fees for input and output tokens.
      Do not miss any models in the entire content
    prompt_file: "none"
    pydantic_model: |
      root: Shadergraph Node Library
      ├── Graph nodes (9 categories in total)
      │   │   ├── Sub-category: Adjustment
      │   │   │   ├── Node: Channel Mixer Node; Description: Controls the amount each of the channels of...
      │   │   │   ├── Node: Contrast Node; Description: Adjusts the contrast of...
      │   │   │   └── (... other nodes with descriptions)
      │   │   ├── Sub-category: Blend
      │   │   │   └── Blend Node; Description: Blends the value of...
      │   │   ├── Sub-category: Filter
      │   │   │   └── (... other nodes with descriptions)
      │   │   └── (... other sub-categories, containing nodes with descriptions)
      │   ├── Topic: Channel
      │   │   ├── Node: Append Node; Description: Creates a new vector Out by... 
      │   │   ├── Node: Combine Node; Description: Creates new vectors from... 
      │   │   └── (... other nodes with descriptions)
      │   ├── Topic: Custom Render Texture nodes
      │   │   └── (... other sub-categories OR nodes)
      │   └── (...9 topics in total)
      └── Block nodes
    llm: "openrouter_gpt4o-mini"
    temperature: 0.0
    top_p: 0.9
    max_tokens: 4000
    out_file: "shadergraph_gpt4o-mini"
    headless: true
    cache_mode: "BYPASS"
    word_count_threshold: 1
    page_timeout: 80000





