common:
  out_folder: "output"

sources:
  - id: "shadergraph_nodes_opengpt4o-mini"
    url: "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Node-Library.html"
    urls:
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Node-Library.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Artistic-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Channel-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Custom-Render-Texture-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Input-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Math-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Procedural-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/ui-nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Utility-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/UV-Nodes.html"
    title: "Unity Shadergraph node library structure"
    description: "Extract the hierarchical structure of Unity ShaderGraph nodes, including categories, subcategories, and individual nodes with descriptions. Require graph_nodes arrays with nested categories and nodes."
    instruction: |
      From the crawled content of this page, extract Unity ShaderGraph nodes, categories, or subcategories present.
      Output a single NodeLibrary object.
      - If this page is the main Node Library page, populate graph_nodes with category objects (name only, no subcategories or nodes), and block_nodes similarly.
      - If this page is a category page (e.g., Artistic Nodes), populate graph_nodes with a single category object containing its name, and either subcategories (if the page has sections like Adjustment, Blend) with their nodes, or direct nodes if no subcategories.
      - Do not output multiple objects or empty categories. Ensure subcategories are nested under their parent category.
      - Only include data actually present on the page.
    prompt_file: "none"
    pydantic_model: |
      from pydantic import BaseModel, Field
      from typing import List, Optional

      class ShaderNode(BaseModel):
          name: str = Field(..., description="Name of the shader node.")
          description: str = Field(..., description="Description of the shader node.")

      class Subcategory(BaseModel):
          name: str = Field(..., description="Name of the subcategory.")
          nodes: List[ShaderNode] = Field(..., description="List of nodes in this subcategory.")

      class Category(BaseModel):
          name: str = Field(..., description="Name of the category.")
          subcategories: Optional[List[Subcategory]] = Field(None, description="List of subcategories, if any.")
          nodes: Optional[List[ShaderNode]] = Field(None, description="List of nodes directly in this category, if no subcategories.")

      class NodeLibrary(BaseModel):
          graph_nodes: List[Category] = Field(..., description="List of graph node categories.")
          block_nodes: List[Category] = Field(..., description="List of block node categories.")
    llm: "openrouter_gpt4o-mini"
    temperature: 0.0
    top_p: 0.9
    max_tokens: 8000
    out_file: "shadergraph_nodes_gpt4o-mini"
    extraction_type: "schema"
    css_selector: null
    headless: true
    cache_mode: "BYPASS"
    word_count_threshold: 1
    page_timeout: 80000
    workflow: "llm"

  - id: "shadergraph_categories_opengpt4o-mini"
    url: "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Node-Library.html"
    title: "Unity Shadergraph category page"
    description: "Extract the Unity ShaderGraph categories from the url."
    instruction: |
      From the crawled content of this page, extract Unity ShaderGraph categories.
      Output a single NodeLibrary object.
      - If this page is the main Node Library page, categories with descriptions. Skip block_nodes similarly.
      - Only include data actually present on the page.
    prompt_file: "none"
    pydantic_model: |
      from pydantic import BaseModel, Field
      from typing import List, Optional

      class ShaderNode(BaseModel):
          name: str = Field(..., description="Name of the shader node.")
          description: str = Field(..., description="Description of the shader node.")

      class Subcategory(BaseModel):
          name: str = Field(..., description="Name of the subcategory.")
          nodes: List[ShaderNode] = Field(..., description="List of nodes in this subcategory.")

      class Category(BaseModel):
          name: str = Field(..., description="Name of the category.")
          subcategories: Optional[List[Subcategory]] = Field(None, description="List of subcategories, if any.")
          nodes: Optional[List[ShaderNode]] = Field(None, description="List of nodes directly in this category, if no subcategories.")

      class NodeLibrary(BaseModel):
          graph_nodes: List[Category] = Field(..., description="List of graph node categories.")
          block_nodes: List[Category] = Field(..., description="List of block node categories.")
    llm: "openrouter_gpt4o-mini"
    temperature: 0.0
    top_p: 0.9
    max_tokens: 8000
    out_file: "shadergraph_categories"
    extraction_type: "schema"
    css_selector: null
    headless: true
    cache_mode: "BYPASS"
    word_count_threshold: 1
    page_timeout: 80000
    workflow: "llm"


  - id: "shadergraph_toc_explore"
    url: "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Node-Library.html"
    urls:
    title: "Unity Shadergraph node library structure based on sidebar"
    description: "Extract the hierarchical structure of Unity ShaderGraph nodes, including categories, subcategories, and individual nodes with descriptions. Require graph_nodes arrays with nested categories and nodes."
    instruction: |
      From the URL focus on the sidebar. It represents structure of the topics in Shadergaph documentation.
      - Extract the entire sidebar structure, starting with "About Shadergraph" and ending with Samples/Terrain Shaders/Performance Comparison
      - Save as well structured Markdown, preserving nested hierarchy.
    prompt_file: "none"
    pydantic_model: null
    llm: null
    temperature: 0.0
    top_p: 0.9
    max_tokens: 8000
    out_file: "shadergraph_toc_explore"
    out_format: ["markdown", "json"]
    extraction_type: "block"
    css_selector: "#toc"
    headless: true
    cache_mode: "BYPASS"
    word_count_threshold: 1
    page_timeout: 80000
    workflow: "explore"
    deep_crawl: false
    max_depth: 3
    max_pages: 10

  - id: "shadergraph_content_explore"
    url: "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Node-Library.html"
    urls:
    title: "Unity Shadergraph node library structure based on iframe"
    description: "Extract the hierarchical structure of Unity ShaderGraph nodes, including categories, subcategories, and individual nodes with descriptions. Require graph_nodes arrays with nested categories and nodes."
    instruction: |
      From the URL focus on the page content, not the sidebar. It contains tables with links to Shadergraph categories, which in turn contain sub-category tables with Shadergraph nodes.
      - Extract the entire Shadergrah Nodes structure, and list all nodes under their correct categories.
      - Save as well structured Markdown, preserving nested hierarchy.
    prompt_file: "none"
    pydantic_model: null
    llm: null
    temperature: 0.0
    top_p: 0.9
    max_tokens: 8000
    out_file: "shadergraph_content"
    out_format: ["markdown", "json"]
    extraction_type: "block"
    css_selector: "#_content"
    headless: true
    cache_mode: "BYPASS"
    word_count_threshold: 1
    page_timeout: 80000
    # Allowed workflow values: 'llm' (uses LLM for structured extraction with Pydantic models), 'explore' (basic crawling without LLM/Pydantic)
    workflow: "explore"
    # For explore workflow: enable deep crawling to follow links up to max_depth levels
    deep_crawl: true
    # Maximum depth for deep crawling (default: 3)
    max_depth: 4
    # Maximum number of pages to crawl (default: 10)
    max_pages: 50
    # Filters for deep crawling (optional)
    filters:
      - type: DomainFilter
        allowed_domains: ["docs.unity3d.com"]
      - type: URLPatternFilter
        patterns: ["*Nodes.html", "*Node.html"]
        # blocked_patterns: ["*Block-Node.html"]
      # - type: ContentRelevanceFilter
      #   query: "Unity ShaderGraph node documentation, categories like Artistic, Channel, Math, Procedural"
      #   threshold: 0.6
      # - type: ContentTypeFilter
      #   allowed_types: ["text/html", "application/json"]
      # - type: SEOFilter
      #   threshold: 0.5
      #   keywords: ["shader", "node", "unity"]

  - id: "shadergraph_content_dom"
    workflow: "dom"
    url: "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Node-Library.html"
    urls:
    title: "Unity Shadergraph node library structure based on DOM selectors"
    description: "Extract the hierarchical structure of Unity ShaderGraph nodes using DOM selectors."
    instruction: null
    prompt_file: "none"
    pydantic_model: null
    llm: null
    temperature: 0.0
    top_p: 0.9
    max_tokens: 8000
    out_file: "shadergraph_content"
    out_format: "json"
    extraction_type: null
    css_selector: "#_content"
    headless: true
    cache_mode: "BYPASS"
    word_count_threshold: 1
    page_timeout: 80000
    expand_nodes: true
    preview_limit: 2
    category_schema:
      name: "ShaderGraph Categories"
      baseSelector: "div:first-of-type table tbody tr"  # First div's table body rows for graph nodes categories
      fields:
        - name: "category_name"
          selector: "a"  # Link text
          type: "text"
        - name: "category_url"
          selector: "a"
          type: "attribute"
          attribute: "href"
        - name: "description"
          selector: "td:nth-child(2)"  # Second column for description
          type: "text"
    node_schema:
      name: "ShaderGraph Nodes"
      baseSelector: "table tbody tr"  # Table body rows for nodes on category pages
      fields:
        - name: "node_name"
          selector: "a"  # Link text
          type: "text"
        - name: "node_url"
          selector: "a"
          type: "attribute"
          attribute: "href"
    node_detail_schema:
      name: "Node Details"
      baseSelector: "body"
      fields:
        - name: "name"
          selector: "h1:first-of-type"
          type: "text"
        - name: "description"
          selector: "h2:first-of-type + p"
          type: "text"

  - id: "houdini_content_dom"
    workflow: "dom"
    url: "https://www.sidefx.com/docs/houdini21.0/nodes/index.html"
    urls:
    title: "Unity Shadergraph node library structure based on DOM selectors"
    description: "Extract the hierarchical structure of Unity ShaderGraph nodes using DOM selectors."
    instruction: null
    prompt_file: "none"
    pydantic_model: null
    llm: null
    temperature: 0.0
    top_p: 0.9
    max_tokens: 8000
    out_file: "houdini_content"
    out_format: "json"
    extraction_type: null
    css_selector: "#subtopics-body"
    headless: true
    cache_mode: "BYPASS"
    word_count_threshold: 1
    page_timeout: 80000
    schema:
      name: "Houdini Node Categories"
      baseSelector: "li"  # List items for categories
      fields:
        - name: "category_name"
          selector: "a"  # Link text
          type: "text"
        - name: "category_url"
          selector: "a"
          type: "attribute"
          attribute: "href"
        - name: "description"
          selector: "p:nth-of-type(2)"  # Second paragraph for description
          type: "text"

  - id: "shadergraph_hierarchy"
    title: "Build hierarchical structure from explore output"
    description: "Process the flat crawled data from explore workflow and build a hierarchical JSON structure of ShaderGraph nodes"
    input_file: "shadergraph_content.json"
    out_file: "shadergraph_hierarchy"
    url: "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Node-Library.html"
    workflow: "hierarchy"


  - id: "shadergraph_content_pydantic"
    url: "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Node-Library.html"
    urls:
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Node-Library.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Artistic-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Channel-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Custom-Render-Texture-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Input-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Math-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Procedural-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/ui-nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/Utility-Nodes.html"
      - "https://docs.unity3d.com/Packages/com.unity.shadergraph@17.4/manual/UV-Nodes.html"
    title: "Generate Pydantic models from explore JSON"
    description: "Use LLM to analyze the explore JSON output and generate appropriate Pydantic models for the hierarchical structure"
    instruction: |
      From the crawled content of this page, extract Unity ShaderGraph nodes, categories, or subcategories present.
      Output a single NodeLibrary object.
      - If this page is the main Node Library page, populate graph_nodes with category objects (name only, no subcategories or nodes), and block_nodes similarly.
      - If this page is a category page (e.g., Artistic Nodes), populate graph_nodes with a single category object containing its name, and either subcategories (if the page has sections like Adjustment, Blend) with their nodes, or direct nodes if no subcategories.
      - Do not output multiple objects or empty categories. Ensure subcategories are nested under their parent category.
      - Only include data actually present on the page.
    prompt: |
      You are provided with the output from an explore workflow: a JSON file containing a list of pages with their URLs and raw markdown content, and a markdown file with combined content.

      The site is the Unity ShaderGraph Node Library documentation. The structure is hierarchical:

      - Root: NodeLibrary with graph_nodes and block_nodes (both lists of Category)

      - Category: name, url (optional), description (optional), subcategories (optional list of Subcategory), nodes (optional list of Node)

      - Subcategory: name, anchor (optional), nodes (list of Node)

      - Node: name, url (optional), description (optional)

      Analyze the provided data to understand the exact hierarchy and fields present.

      Generate appropriate Pydantic BaseModel classes in Python that accurately represent this structure.

      Include proper field types (str, List, Optional), descriptions using Field, and relationships.

      Ensure the models can be used for schema-based extraction.

      Output only the Python code for the models, starting with necessary imports and class definitions. No explanations or markdown.
    prompt_file: "none"
    pydantic_model: null
    llm: "openrouter_gpt4o-mini"
    temperature: 0.0
    top_p: 0.9
    max_tokens: 16000
    out_file: "shadergraph_content"
    headless: true
    cache_mode: "BYPASS"
    word_count_threshold: 1
    page_timeout: 80000
    workflow: "pydantic"
