sources:
  - id: openai_fees_v1
    title: "OpenAI pricing schema guidance"
    description: "Prompt and settings to extract model pricing and glossary from pricing pages. Require models array with model_name, input_cost, output_cost, units, notes; require glossary listing all fields"
    guidance_file: guidance_openAI_fees_gpt4o_v2
    prompt_file: prompt_schema_discovery.md
    model: gpt-4o
    temperature: 0.0
    top_p: 0.9
    max_tokens: 4000
    out_file: openai_fees

  - id: unity_shadergraph_v1
    title: "Unity Shadergraph Node Documentation"
    description: "Extract Graph node topics from Unity Shadergraph documentation"
    # small guidance may be embedded directly in a prompt file; prefer using prompt files for long multi-line guidance
    guidance_file: prompt_Unity_Shadergraph_gpt41.md
    prompt_file: prompt_Unity_Shadergraph_gpt41.md
    model: oss
    temperature: 0.0
    top_p: 0.9
    max_tokens: 4000
    out_file: unity_shadergraph
