from pydantic import BaseModel, Field
from typing import Optional, Any
from typing import List, Optional

class DiscoveredModel_Sectionsitem_Linksitem(BaseModel):
    text: Optional[str] = Field(..., description="Text of the link.", example="Batch API")
    url: Optional[str] = Field(..., description="URL the link points to.", example="https://platform.openai.com/docs/guides/batch")

class DiscoveredModel_Sectionsitem(BaseModel):
    sectionTitle: Optional[str] = Field(..., description="Title of the section.", example="Pricing reflects standard processing rates.")
    links: Optional[List[DiscoveredModel_Sectionsitem_Linksitem]] = Field(..., description="List of links in the section.", example={"text": "Batch API", "url": "https://platform.openai.com/docs/guides/batch"})

class DiscoveredModel(BaseModel):
    title: Optional[str] = Field(..., description="The main title of the page.", example="API Pricing")
    sections: Optional[List[DiscoveredModel_Sectionsitem]] = Field(..., description="List of sections on the pricing page.", example={"sectionTitle": "Pricing reflects standard processing rates.", "links": [{"text": "Batch API", "url": "https://platform.openai.com/docs/guides/batch"}]})

# Field glossary (generated by LLM)
# ````json
# [
#   {
#     "name": "title",
#     "description": "The main title of the page.",
#     "examples": [
#       "API Pricing"
#     ]
#   },
#   {
#     "name": "sections",
#     "description": "List of sections on the pricing page.",
#     "examples": []
#   },
#   {
#     "name": "sectionTitle",
#     "description": "Title of the section.",
#     "examples": [
#       "Pricing reflects standard processing rates."
#     ]
#   },
#   {
#     "name": "links",
#     "description": "List of links in the section.",
#     "examples": []
#   },
#   {
#     "name": "text",
#     "description": "Text of the link.",
#     "examples": [
#       "Batch API"
#     ]
#   },
#   {
#     "name": "url",
#     "description": "URL the link points to.",
#     "examples": [
#       "https://platform.openai.com/docs/guides/batch"
#     ]
#   }
# ]
# ````
